"""empty message

Revision ID: 13e7c3e0687b
Revises: 5e42a9875bc9
Create Date: 2025-01-28 10:01:40.611910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e7c3e0687b'
down_revision = '5e42a9875bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('settled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('settled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
