"""empty message

Revision ID: 5e42a9875bc9
Revises: c1b7a02fef16
Create Date: 2025-01-27 17:53:48.524895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e42a9875bc9'
down_revision = 'c1b7a02fef16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_participants', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_expense_user', ['expense_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_expense_user', type_='unique')

    # ### end Alembic commands ###
